### ISSUE TITLE
初始化连接不到数据库，报错

### ISSUE THREAD

**Issue by joket1999** [welkinwong/nodercms#30]
```shell
[2019-05-28 03:25:55.455] [INFO] system - 正在监听 port 3000
[2019-05-28 03:26:00.425] [INFO] access - GET /admin/install
[2019-05-28 03:26:00.427] [ERROR] console - (node:870) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
[2019-05-28 03:26:00.527] [INFO] access - GET /assets/admin/main.css
[2019-05-28 03:26:00.552] [INFO] access - GET /assets/admin/main.js
[2019-05-28 03:26:00.554] [INFO] access - GET /assets/admin/vendor.css
[2019-05-28 03:26:00.561] [INFO] access - GET /assets/admin/views.js
[2019-05-28 03:26:00.582] [INFO] access - GET /assets/admin/vendor.js
[2019-05-28 03:26:00.810] [WARN] access - GET /api/install
[2019-05-28 03:26:00.903] [INFO] access - GET /assets/admin/images/logo-lg.png
[2019-05-28 03:26:00.908] [INFO] access - GET /assets/admin/images/sponsor/weixin99.jpg
[2019-05-28 03:26:00.910] [INFO] access - GET /assets/admin/images/sponsor/weixin199.jpg
[2019-05-28 03:26:00.918] [INFO] access - GET /assets/admin/images/sponsor/weixin499.jpg
[2019-05-28 03:26:00.929] [INFO] access - GET /assets/admin/images/sponsor/weixin999.jpg
[2019-05-28 03:26:00.931] [INFO] access - GET /assets/admin/images/sponsor/alipay199.jpg
[2019-05-28 03:26:00.932] [INFO] access - GET /assets/admin/images/sponsor/alipay99.jpg
[2019-05-28 03:26:00.938] [INFO] access - GET /assets/admin/images/sponsor/alipay499.jpg
[2019-05-28 03:26:00.941] [INFO] access - GET /assets/admin/images/sponsor/alipay999.jpg
[2019-05-28 03:26:01.048] [WARN] access - GET /api/install/themes
[2019-05-28 03:26:02.855] [ERROR] console - (node:870) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
[2019-05-28 03:26:02.864] [WARN] console - Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
[2019-05-28 03:26:02.868] [ERROR] access - PUT /api/install/test-database
[2019-05-28 03:26:02.872] [WARN] console - Unhandled rejection MongoError: Authentication failed.
    at Function.MongoError.create (/home/nodercms/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at /home/nodercms/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:497:72
    at authenticateStragglers (/home/nodercms/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:443:16)
    at Connection.messageHandler (/home/nodercms/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:477:5)
    at Socket.<anonymous> (/home/nodercms/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:331:22)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at Socket.Readable.push (_stream_readable.js:226:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)

[2019-05-28 03:26:02.888] [INFO] access - GET /assets/admin/fonts/fontawesome-webfont.woff2?v=4.6.1

```

**Comment by falost** [comment]
`Unhandled rejection MongoError: Authentication failed. `
目测你没有数据库权限
