### ISSUE TITLE
 安装请求失败，请尝试重启服务器与数据库并重新安装

### ISSUE THREAD

**Issue by 13751139402** [welkinwong/nodercms#39]
安装请求失败，请尝试重启服务器与数据库并重新安装
![微信截图_20201031170559](https://user-images.githubusercontent.com/48110405/97775417-65660e00-1b9b-11eb-836c-6d9241806c6d.png)
不知道怎么回事，mongoDB已经连接成功了，但是安装不了

**Comment by welkinwong** [comment]
1. 清空数据库
2. 确保mongoDB开启了鉴权模式，同时 a超级用户已建立 b数据库用户已建立并拥有readWrite权限 （详见官网帮助中心）
3. 重新执行安装流程

**Comment by niaolianyu** [comment]
找了 好几个 版本的 cms 这个比较简洁 感谢作者提供 这么完善的 软件 
遇到 和  13751139402 一样的问题
node 14.15.1 mongodb 4.4.2  
试过 其他版本 4.0.21 3.6.21 3.3.22 均报 这个错误

后台 错误信息如下 
[2020-11-26 22:57:06.703] [INFO] system - 正在监听 port 3000
[2020-11-26 22:57:08.573] [WARN] access - GET /admin/install
[2020-11-26 22:57:08.574] [ERROR] console - (node:3172) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
[2020-11-26 22:57:08.599] [WARN] access - GET /assets/admin/vendor.css
[2020-11-26 22:57:08.602] [WARN] access - GET /assets/admin/main.css
[2020-11-26 22:57:08.607] [WARN] access - GET /assets/admin/vendor.js
[2020-11-26 22:57:08.610] [WARN] access - GET /assets/admin/main.js
[2020-11-26 22:57:08.611] [WARN] access - GET /assets/admin/views.js
[2020-11-26 22:57:08.680] [WARN] access - GET /api/install
[2020-11-26 22:57:08.709] [WARN] access - GET /api/install/themes
[2020-11-26 22:57:08.719] [WARN] access - GET /assets/admin/images/logo-lg@2x.png
[2020-11-26 22:57:08.721] [WARN] access - GET /assets/admin/images/sponsor/weixin.png
[2020-11-26 22:57:08.726] [WARN] access - GET /assets/admin/images/sponsor/alipay.jpg
[2020-11-26 22:57:14.548] [ERROR] console - (node:3172) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
[2020-11-26 22:57:14.559] [WARN] console - Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
[2020-11-26 22:57:14.569] [INFO] access - PUT /api/install/test-database
[2020-11-26 23:00:04.218] [WARN] console - Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
[2020-11-26 23:00:04.224] [INFO] access - PUT /api/install/test-database
internal/fs/utils.js:781
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type boolean (true)
    at Object.writeFile (fs.js:1436:5)
    at Array.async.auto.writeInstallLock (D:\project\nodejs\nodercms-1.4.2\core\services\install.service.js:147:10)
    at listener (D:\project\nodejs\nodercms-1.4.2\node_modules\async\lib\async.js:605:42)
    at D:\project\nodejs\nodercms-1.4.2\node_modules\async\lib\async.js:544:17
    at _arrayEach (D:\project\nodejs\nodercms-1.4.2\node_modules\async\lib\async.js:85:13)
    at Immediate.taskComplete [as _onImmediate] (D:\project\nodejs\nodercms-1.4.2\node_modules\async\lib\async.js:543:13)
    at processImmediate (internal/timers.js:461:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodercms@1.4.2 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodercms@1.4.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

debuglog如下
10 silly lifecycle nodercms@1.4.2~start: Args: [ '/d /s /c', 'node ./bin/www' ]
11 silly lifecycle nodercms@1.4.2~start: Returned: code: 1  signal: null
12 info lifecycle nodercms@1.4.2~start: Failed to exec start script
13 verbose stack Error: nodercms@1.4.2 start: `node ./bin/www`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\other\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (D:\other\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid nodercms@1.4.2
15 verbose cwd D:\project\nodejs\nodercms-1.4.2
16 verbose Windows_NT 10.0.17763
17 verbose argv "D:\\other\\nodejs\\node.exe" "D:\\other\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v14.15.1
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error nodercms@1.4.2 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the nodercms@1.4.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by niaolianyu** [comment]
找到问题原因 core\services  install.service  147 行 fs.writeFile('install.lock', "true", function (err) {

这里的true 字符串 类型 修改 即可

**Comment by niaolianyu** [comment]
找到问题原因 core\services install.service 147 行 fs.writeFile('install.lock', "true", function (err) {

这里的true 字符串 类型 修改 即可

**Comment by TimeSenz** [comment]
上面的问题已经解决了，还是遇到同样的情况，报错如下：

```
[2020-12-23 13:06:51.882] [ERROR] console - (node:21379) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
[2020-12-23 13:06:51.890] [WARN] console - Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
```

根据报错找到文档，，大概意思是说版本更新了，需要在连接的时候设置`useMongoClient`这个参数的值为true
所以在代码`lib/database.lib.js`中修改一下
```
     function (config, callback) {
       mongoose.connect('mongodb://' + config.host + ':' + config.port + '/' + config.db, {
         user: config.user,
         pass: config.pass
+        useMongoClient:true
       }, function (err) {
         if (err) {
           err.type = 'database';
```

添加这个参数后，问题解决

**Comment by demonxwj** [comment]
useMongoClient:true  增加了这个属性依旧不行

**Comment by html9527** [comment]
有人解决了这个问题吗?我也是不行

**Comment by falost** [comment]
> ?

确保你的数据库信息是正确的

**Comment by wugy0103** [comment]
这是来自QQ邮箱的自动回复邮件。
