### ISSUE TITLE
Trying to open unclosed connection

### ISSUE THREAD

**Issue by JZLeung** [welkinwong/nodercms#8]
```
[2017-07-10 12:21:41.966] [ERROR] database - { Error: Trying to open unclosed connection.
    at NativeConnection.Connection._handleOpenArgs (/home/wwwroot/default/nodercms/node_modules/mongoose/lib/connection.js:213:11)
    at NativeConnection.<anonymous> (/home/wwwroot/default/nodercms/node_modules/mongoose/lib/connection.js:308:37)
    at NativeConnection.deprecated [as open] (internal/util.js:67:15)
    at Mongoose.connect (/home/wwwroot/default/nodercms/node_modules/mongoose/lib/index.js:272:47)
    at /home/wwwroot/default/nodercms/lib/database.lib.js:103:16
    at fn (/home/wwwroot/default/nodercms/node_modules/async/lib/async.js:746:34)
    at /home/wwwroot/default/nodercms/node_modules/async/lib/async.js:1213:16
    at /home/wwwroot/default/nodercms/node_modules/async/lib/async.js:166:37
    at /home/wwwroot/default/nodercms/node_modules/async/lib/async.js:706:43
    at /home/wwwroot/default/nodercms/node_modules/async/lib/async.js:167:37
    at /home/wwwroot/default/nodercms/node_modules/async/lib/async.js:1209:30
    at /home/wwwroot/default/nodercms/lib/database.lib.js:99:9
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3) state: 1, type: 'database' }
[2017-07-10 12:21:41.968] [WARN] console - Unhandled rejection Error: Trying to open unclosed connection.
    at NativeConnection.Connection._handleOpenArgs (/home/wwwroot/default/nodercms/node_modules/mongoose/lib/connection.js:213:11)
    at NativeConnection.<anonymous> (/home/wwwroot/default/nodercms/node_modules/mongoose/lib/connection.js:308:37)
    at NativeConnection.deprecated [as open] (internal/util.js:67:15)
    at Mongoose.connect (/home/wwwroot/default/nodercms/node_modules/mongoose/lib/index.js:272:47)
    at /home/wwwroot/default/nodercms/lib/database.lib.js:103:16
    at fn (/home/wwwroot/default/nodercms/node_modules/async/lib/async.js:746:34)
    at /home/wwwroot/default/nodercms/node_modules/async/lib/async.js:1213:16
    at /home/wwwroot/default/nodercms/node_modules/async/lib/async.js:166:37
    at /home/wwwroot/default/nodercms/node_modules/async/lib/async.js:706:43
    at /home/wwwroot/default/nodercms/node_modules/async/lib/async.js:167:37
    at /home/wwwroot/default/nodercms/node_modules/async/lib/async.js:1209:30
    at /home/wwwroot/default/nodercms/lib/database.lib.js:99:9
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

[2017-07-10 12:21:41.968] [ERROR] access - POST /api/install
```
node: 6.9.1
mongodb: 3.4.6

db.auth()认证通过，返回1.

**Comment by welkinwong** [comment]
确认，应该是出现在安装过程，但是属于偶发，你可以重新执行一遍安装程序，应该可以顺利安装；具体原因为测试数据库连接的时候关闭没有回调导致后续重复打开，最新版会修复这个问题
